---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[yasm::default]
    attributes:
      yasm:
        install_method: source
